USE [TESTDB]
GO

/****** Object:  Table [dbo].[Synchronize_Log]    Script Date: 2019-05-31 09:27:23 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[Synchronize_Log](
	[ID] [INT] IDENTITY(1,1) NOT NULL,
	[DbName] [VARCHAR](50) NULL,
	[SynID] [INT] NULL,
	[JsonText_Msg] [VARCHAR](2000) NULL,
	[InsDate] [VARCHAR](23) NULL,
	[SuccessCode] [VARCHAR](10) NULL,
	[MsgText] [VARCHAR](100) NULL,
	[DataText] [VARCHAR](1000) NULL,
 CONSTRAINT [PK__Synchron__3214EC272DE6D218] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


